
package cn.com.weaver.services.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LoginLogService", targetNamespace = "webservices.services.weaver.com.cn", wsdlLocation = "http://172.16.60.63:8080//services/LoginLogService?wsdl")
public class LoginLogService
    extends Service
{

    private final static URL LOGINLOGSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOGINLOGSERVICE_EXCEPTION;
    private final static QName LOGINLOGSERVICE_QNAME = new QName("webservices.services.weaver.com.cn", "LoginLogService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.60.63:8080//services/LoginLogService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOGINLOGSERVICE_WSDL_LOCATION = url;
        LOGINLOGSERVICE_EXCEPTION = e;
    }

    public LoginLogService() {
        super(__getWsdlLocation(), LOGINLOGSERVICE_QNAME);
    }

    public LoginLogService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOGINLOGSERVICE_QNAME, features);
    }

    public LoginLogService(URL wsdlLocation) {
        super(wsdlLocation, LOGINLOGSERVICE_QNAME);
    }

    public LoginLogService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOGINLOGSERVICE_QNAME, features);
    }

    public LoginLogService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoginLogService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LoginLogServicePortType
     */
    @WebEndpoint(name = "LoginLogServiceHttpPort")
    public LoginLogServicePortType getLoginLogServiceHttpPort() {
        return super.getPort(new QName("webservices.services.weaver.com.cn", "LoginLogServiceHttpPort"), LoginLogServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoginLogServicePortType
     */
    @WebEndpoint(name = "LoginLogServiceHttpPort")
    public LoginLogServicePortType getLoginLogServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("webservices.services.weaver.com.cn", "LoginLogServiceHttpPort"), LoginLogServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOGINLOGSERVICE_EXCEPTION!= null) {
            throw LOGINLOGSERVICE_EXCEPTION;
        }
        return LOGINLOGSERVICE_WSDL_LOCATION;
    }

}
