
package cn.com.weaver.services.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* WorkflowService service = new WorkflowService();
* WorkflowServicePortType portType = service.getWorkflowServiceHttpPort();
* portType.getAllWorkflowRequestList(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "WorkflowService", targetNamespace = "webservices.services.weaver.com.cn", wsdlLocation = "http://172.16.60.63:8080//services/WorkflowService?wsdl")
public class WorkflowService extends Service {

	private final static URL WORKFLOWSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(cn.com.weaver.services.webservices.WorkflowService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = cn.com.weaver.services.webservices.WorkflowService.class.getResource(".");
			url = new URL(baseUrl, "http://172.16.60.63:8080//services/WorkflowService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://172.16.60.63:8080//services/WorkflowService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		WORKFLOWSERVICE_WSDL_LOCATION = url;
	}

	public WorkflowService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public WorkflowService() {
		super(WORKFLOWSERVICE_WSDL_LOCATION, new QName("webservices.services.weaver.com.cn", "WorkflowService"));
	}

	/**
	 * 
	 * @return returns WorkflowServicePortType
	 */
	@WebEndpoint(name = "WorkflowServiceHttpPort")
	public WorkflowServicePortType getWorkflowServiceHttpPort() {
		return super.getPort(new QName("webservices.services.weaver.com.cn", "WorkflowServiceHttpPort"),
				WorkflowServicePortType.class);
	}

}
